# Generated by Django 5.2.10 on 2026-01-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, db_index=True, help_text='Username без @', max_length=32, verbose_name='Telegram Username'),
        ),
    ]
