# Generated by Django 5.2.10 on 2026-01-16 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_favorite_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Дата')),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='Новых пользователей')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='Активных пользователей (DAU)')),
                ('total_events', models.PositiveIntegerField(default=0, verbose_name='Всего событий')),
                ('product_views', models.PositiveIntegerField(default=0, verbose_name='Просмотров товаров')),
                ('product_clicks', models.PositiveIntegerField(default=0, verbose_name='Кликов на товары')),
                ('cart_adds', models.PositiveIntegerField(default=0, verbose_name='Добавлений в корзину')),
                ('cart_removes', models.PositiveIntegerField(default=0, verbose_name='Удалений из корзины')),
                ('searches', models.PositiveIntegerField(default=0, verbose_name='Поисковых запросов')),
                ('orders', models.PositiveIntegerField(default=0, verbose_name='Заказов')),
                ('revenue', models.PositiveIntegerField(default=0, verbose_name='Выручка (копейки)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Дневная статистика',
                'verbose_name_plural': 'Дневная статистика',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event_type', models.CharField(choices=[('app_open', 'Открытие приложения'), ('product_view', 'Просмотр товара'), ('product_click', 'Клик на товар'), ('cart_add', 'Добавление в корзину'), ('cart_remove', 'Удаление из корзины'), ('category_view', 'Просмотр категории'), ('search', 'Поисковый запрос'), ('checkout_start', 'Начало оформления'), ('order_complete', 'Заказ оформлен')], db_index=True, max_length=30, verbose_name='Тип события')),
                ('search_query', models.CharField(blank=True, max_length=255, verbose_name='Поисковый запрос')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные события (цена, количество и т.д.)', verbose_name='Метаданные')),
                ('event_date', models.DateField(db_index=True, verbose_name='Дата события')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID сессии')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='products.category', verbose_name='Категория')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='products.product', verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие аналитики',
                'verbose_name_plural': 'События аналитики',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'event_date'], name='analytics_a_event_t_8751f4_idx'), models.Index(fields=['user', 'event_date'], name='analytics_a_user_id_32ea45_idx'), models.Index(fields=['product', 'event_type'], name='analytics_a_product_2e39c1_idx'), models.Index(fields=['category', 'event_type'], name='analytics_a_categor_d25645_idx'), models.Index(fields=['event_date', 'event_type'], name='analytics_a_event_d_0f22c0_idx')],
            },
        ),
    ]
