# Generated by Django 5.2.10 on 2026-01-16 22:11

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStats',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика клиента',
                'verbose_name_plural': 'По клиенту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
