# Generated by Django 5.2.10 on 2026-01-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.CharField(choices=[('about', 'О нас'), ('delivery', 'Доставка'), ('contacts', 'Контакты')], help_text='Уникальный идентификатор страницы', max_length=50, unique=True, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Поддерживает HTML-разметку', verbose_name='Содержимое')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли страницу пользователям', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['slug'],
            },
        ),
    ]
