# Generated by Django 5.2.10 on 2026-01-23 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='ID пользователя в Telegram', unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, help_text='Username в Telegram (без @)', max_length=255, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True, help_text='Может ли использовать админ-команды', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('note', models.TextField(blank=True, help_text='Любая заметка об этом админе', verbose_name='Заметка')),
                ('user', models.OneToOneField(blank=True, help_text='Связанный пользователь (опционально)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_admin', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Админ бота',
                'verbose_name_plural': 'Админы бота',
                'ordering': ['-created_at'],
            },
        ),
    ]
