# Generated by Django 5.2.10 on 2026-01-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botadmin',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Заполняется автоматически при первом использовании', null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='botadmin',
            name='username',
            field=models.CharField(help_text='Username в Telegram (например @username)', max_length=255, unique=True, verbose_name='Username'),
        ),
    ]
