# Generated by Django 5.2.10 on 2026-01-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_botadmin_telegram_id_alter_botadmin_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='Состояние')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Состояние разговора',
                'verbose_name_plural': 'Состояния разговоров',
            },
        ),
    ]
