# Generated by Django 5.2.10 on 2026-01-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_conversationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='segment',
            field=models.CharField(default='all', help_text='ID сегмента для рассылки', max_length=50, verbose_name='Сегмент аудитории'),
        ),
    ]
