# Generated by Django 5.2.10 on 2026-01-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_broadcast_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='segment',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='recipients_usernames',
            field=models.JSONField(blank=True, default=list, help_text='Список username получателей', verbose_name='Получатели (usernames)'),
        ),
    ]
