# Generated by Django 5.2.10 on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_change_segment_to_recipients_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='audience_type',
            field=models.CharField(
                choices=[
                    ('all', 'Всем'),
                    ('customers', 'Покупателям'),
                    ('vip', 'Постоянным клиентам'),
                    ('new', 'Новым (7 дней)'),
                    ('inactive', 'Неактивным (30+ дней)'),
                    ('custom', 'По списку'),
                ],
                default='custom',
                max_length=20,
                verbose_name='Тип аудитории',
            ),
        ),
    ]
