# Generated by Django 5.2.10 on 2026-01-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_add_audience_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='recipients_usernames',
            field=models.JSONField(blank=True, default=list, help_text='Список username получателей (для типа "По списку")', verbose_name='Получатели (usernames)'),
        ),
    ]
