# Generated by Django 5.2.10 on 2026-01-16 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('action', models.CharField(choices=[('added', 'Добавлено'), ('removed', 'Удалено')], db_index=True, max_length=10, verbose_name='Действие')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_actions', to='products.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Действие с избранным',
                'verbose_name_plural': 'История избранного',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='products_fa_user_id_b54465_idx'), models.Index(fields=['product', '-created_at'], name='products_fa_product_50a735_idx'), models.Index(fields=['user', 'product', '-created_at'], name='products_fa_user_id_d10681_idx')],
            },
        ),
    ]
